XProject/XProject.MVC/Models/ErrorViewModel.cs
namespace XProject.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

XProject/XProject.MVC/Controllers/AppPageController.cs
using Microsoft.AspNetCore.Mvc;
using XProject.Application.Interfaces;
using XProject.Domain.Entitities;

namespace XProject.MVC.Controllers
{
    public class AppPageController : Controller
    {
        private readonly IAppPageService _appPageService;

        public AppPageController(IAppPageService appPageService)
        {
            _appPageService = appPageService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<AppPage> pages = await _appPageService.GetAll();

            return View(pages);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeVisibility(string id)
        {
            await _appPageService.ChangeVisibility(id);

            return RedirectToAction("Index");
        }
    }
}

XProject/XProject.MVC/Controllers/FinantialOperationController.cs
using Microsoft.AspNetCore.Mvc;
using XProject.Application.DTOs;
using XProject.Application.Interfaces;
using XProject.Application.ViewModels;
using XProject.Domain.Entitities;
using XProject.MVC.Models;

namespace XProject.MVC.Controllers
{
    public class FinantialOperationController : Controller
    {
        private readonly IFinantialOperationService _finantialOperationService;

        public FinantialOperationController(IFinantialOperationService finantialOperationService)
        {
            _finantialOperationService = finantialOperationService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.FinantialOperations = GetOrderedFinantialOperationList();

            FinantialOperationViewModel newOperation = new();

            return View(newOperation);
        }       

        [HttpPost]
        public async Task<IActionResult> Create(FinantialOperationViewModel newOperation)
        {
            if (ModelState.IsValid)
            {
                await _finantialOperationService.Create(newOperation);

                return RedirectToAction(nameof(Index));
            }

            ViewBag.FinantialOperations = GetOrderedFinantialOperationList();
            return View(nameof(Index), newOperation);
        }

        private List<FinantialOperationViewModel> GetOrderedFinantialOperationList()
        {
            List<FinantialOperationViewModel> operations = _finantialOperationService.GetAll();
            return operations.OrderByDescending(o => o.CreatedAt).ToList();
        }
    }
}

XProject/XProject.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.Diagnostics;
using XProject.Application.Interfaces;
using XProject.Domain;
using XProject.Domain.Enums;
using XProject.MVC.Filters;
using XProject.MVC.Models;

namespace XProject.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAppPageService _appPageService;                

        public HomeController(ILogger<HomeController> logger, IAppPageService appPageService)
        {
            _logger = logger;
            _appPageService = appPageService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [CheckAppPageVisibility(AppPageEnum.Privacy)]
        public IActionResult Privacy()
        {
            return View();
        }

        [RandomAccessFilter]
        public IActionResult RandomPage()
        {
            return View();
        }       

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

XProject/XProject.MVC/Views/AppPage/Index.cshtml
@using XProject.Domain.Entitities;
@model IEnumerable<AppPage>

<h1>Administração de Visibilidade de Páginas</h1>

<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Visibilidade</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pagina in Model)
        {
            <tr>
                <td>@pagina.Name</td>
                <td>
                    <form asp-controller="AppPage" asp-action="ChangeVisibility" method="post">
                        <input type="hidden" name="id" value="@pagina.Id" />
                        <input type="checkbox" @(pagina.IsVisible ? "checked" : "") onchange="this.form.submit()" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

XProject/XProject.MVC/Views/FinantialOperation/Index.cshtml
@using XProject.Application.ViewModels
@model FinantialOperationViewModel

<h2>Create Finantial Operation</h2>

<form asp-action="Create" asp-controller="FinantialOperation" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Value"></label>
        <input asp-for="Value" class="form-control" />
        <span asp-validation-for="Value" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

<h2>List of Finantial Operations</h2>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Value</th>
            <th>Created At</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var operation in ViewBag.FinantialOperations)
        {
            <tr>
                <td>@operation.Id</td>
                <td>@operation.Name</td>
                <td>@operation.Value</td>
                <td>@operation.CreatedAt</td>
            </tr>
        }
    </tbody>
</table>

XProject/XProject.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

XProject/XProject.MVC/Views/Home/RandomPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h3>Well done!</h3>
<p>You achieved reach this page, you have luck!</p>

XProject/XProject.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - XProject.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/XProject.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">XProject.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="RandomPage">Random Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FinantialOperation" asp-action="Index">Finantial Operations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppPage" asp-action="Index">Page Management</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - XProject.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>